#!/usr/bin/env bash
# install and setup haproxy on a new Ubuntu machine

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy

echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 20553-web-01 34.236.38.211 check
    server 20553-web-02 3.236.255.72 check
    option httpchk
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
