#!/usr/bin/env bash
# install and setup haproxy on a new Ubuntu machine

sudo apt-get update
sudo apt-get install -y haproxy

DOMAIN_NAME='vincentondeng.tech'
INIT_FILE='/etc/default/haproxy'

echo "ENABLED=1" >> /etc/default/haproxy

echo "
    frontend vincentondeng.tech
    	bind *:80
    	mode http
    	default_backend vincentondeng.tech
    backend vincentondeng.tech
    	balance roundrobin
	server 20553-web-01 34.236.38.211:80 check
    	server 20553-web-02 3.236.255.72:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
